name: flutter_app
description: A cyberpunk-style toggle app with glowing effects and futuristic UI.
version: 1.0.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/PressStart2P-Regular.ttf
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/fonts/PressStart2P-Regular.ttf
